name: Waka Readme

on:
  schedule:
    - cron: "0 6 * * *"   # Everyday 06:00 UTC
  workflow_dispatch:       

jobs:
  update-readme:
    name: Update README with WakaTime metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_OS: "False"
